---
- name: Check if terraform is installed
  shell: terraform -v
  ignore_errors: True
  register: is_installed

- name: Download zip tarrball
  get_url:
    url: "{{ terraform_artifact_url }}"
    dest: /tmp/terraform.zip
    checksum: "{{ terraform_artifact_sha }}"
  when: is_installed.rc != 0

- name: Extract terraform and make executable
  become: yes
  unarchive: src=/tmp/terraform.zip dest=/usr/local/bin/ mode=755 owner=root group=root
  when: is_installed.rc != 0


- name: Remove terraform.zip
  file: path=/tmp/terraform.zip state=absent

