
- name: Add FP complete apt key
  become: yes
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=575159689BEFB442

- name: Add FP complete apt repo
  become: yes
  apt_repository: repo='deb http://download.fpcomplete.com/debian jessie main' state=present

- name: Install Stack
  become: yes
  apt: name=stack state=installed

- name: Run stack setup for global project
  shell: stack setup

- name: Install global packages
  shell: stack install {{ item }}
  with_items:
    - hledger
    - hledger-web
    - ghc-mod
    - stylish-haskell

