- name: Add Google Chrome key
  become: yes
  apt_key: url="{{ google_chrome_debian_apt_repo_key_url }}" state=present validate_certs=no

- name: Add Google Chrome repo
  become: yes
  apt_repository: repo="{{ google_chrome_debian_apt_repo }}" state=present

- name: Install Google Chrome
  become: yes
  apt: pkg=google-chrome-stable state=installed

