
terraform_version: 0.8.8
terraform_artifact_url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
terraform_artifact_sha: "sha256:403d65b8a728b8dffcdd829262b57949bce9748b91f2e82dfd6d61692236b376"

