
- name: Install XMonad and dependencies
  become: yes
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - conky-all
    - dex
    - dunst
    - dzen2
    - feh
    - libghc-xmonad-contrib-dev
    - libghc-xmonad-extras-dev
    - suckless-tools
    - trayer
    - xfonts-terminus
    - xmobar
    - xmonad
    - xscreensaver
    - xscreensaver-gl
    - xscreensaver-gl-extra

# Workaround xscreensaver delay after resuming from suspend
# See here for more info:  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=781961
- name: Copy over xscreensaver.service
  become: yes
  copy: src=xscreensaver.service dest=/etc/systemd/system/xscreensaver.service
  notify:
    - reload systemd configuration

- name: Enable xscreensaver service
  service: name=xscreensaver enabled=yes

- name: Make sure to link xmonad config
  file: src=/home/deni/dotfiles/xmonad dest=/home/deni/.xmonad owner=deni group=deni state=link

- name: Make sure to link xmobar config
  file: src=/home/deni/dotfiles/xmobarrc dest=/home/deni/.xmobarrc owner=deni group=deni state=link

- name: Make sure to link Xmodmap config
  file: src=/home/deni/dotfiles/Xmodmap dest=/home/deni/.Xmodmap owner=deni group=deni state=link

- name: Make sure to link Xresources config
  file: src=/home/deni/dotfiles/Xresources dest=/home/deni/.Xresources owner=deni group=deni state=link

- name: Make sure dunst config dir exists
  file: path=/home/deni/.config/dunst state=directory

- name: Link dunstrc
  file: src=/home/deni/dotfiles/dunstrc dest=/home/deni/.config/dunst/dunstrc owner=deni group=deni state=link

