
- name: Install XMonad and dependencies
  become: yes
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - dunst
    - feh
    - suckless-tools
    - trayer
    - xmobar
    - xmonad
    - xscreensaver

- name: Make sure to link xmonad config
  file: src=/home/deni/dotfiles/xmonad dest=/home/deni/.xmonad owner=deni group=deni state=link

- name: Make sure to link xmobar config
  file: src=/home/deni/dotfiles/xmobarrc dest=/home/deni/.xmobarrc owner=deni group=deni state=link

- name: Make sure to link Xmodmap config
  file: src=/home/deni/dotfiles/Xmodmap dest=/home/deni/.Xmodmap owner=deni group=deni state=link

- name: Make sure to link Xresources config
  file: src=/home/deni/dotfiles/Xresources dest=/home/deni/.Xresources owner=deni group=deni state=link

