
- name: Install XMonad and dependencies
  become: yes
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - dunst
    - dzen2
    - conky-all
    - feh
    - libghc-xmonad-contrib-dev
    - libghc-xmonad-extras-dev
    - suckless-tools
    - trayer
    - xmobar
    - xmonad
    - xscreensaver
    - xscreensaver-gl
    - xscreensaver-gl-extra

- name: Make sure to link xmonad config
  file: src=/home/deni/dotfiles/xmonad dest=/home/deni/.xmonad owner=deni group=deni state=link

- name: Make sure to link xmobar config
  file: src=/home/deni/dotfiles/xmobarrc dest=/home/deni/.xmobarrc owner=deni group=deni state=link

- name: Make sure to link Xmodmap config
  file: src=/home/deni/dotfiles/Xmodmap dest=/home/deni/.Xmodmap owner=deni group=deni state=link

- name: Make sure to link Xresources config
  file: src=/home/deni/dotfiles/Xresources dest=/home/deni/.Xresources owner=deni group=deni state=link

- name: Make sure dunst config dir exists
  file: path=/home/deni/.config/dunst state=directory

- name: Link dunstrc
  file: src=/home/deni/dotfiles/dunstrc dest=/home/deni/.config/dunst/dunstrc owner=deni group=deni state=link

