- name: Add Dropbox apt key
  become: yes
  apt_key: keyserver="{{ dropbox_debian_apt_repo_keyserver_url }}" id="{{ dropbox_debian_apt_repo_key_id }}"

- name: Install dropbox apt repo
  become: yes
  apt_repository: repo="{{ dropbox_debian_apt_repo }}" state=present

- name: Install dropbox package
  become: yes
  apt: name=dropbox state=present

