- name: Does the Dropbox apt file exist?
  become: yes
  command: test -f /etc/apt/sources.list.d/dropbox.list
  register: dropbox_apt_exists
  ignore_errors: True

- name: Download dropbox package
  get_url:
    url={{ dropbox_deb_url }}
    dest={{ dropbox_deb_local_path }}
    # validate_certs=no   ## FIXME!!!
  when: dropbox_apt_exists.rc == 1

- name: Install dropbox package
  become: yes
  apt: deb={{ dropbox_deb_local_path }}
  when: dropbox_apt_exists.rc == 1


