set encoding=utf-8
set sts=4
set sw=4
set et
au Filetype python setl et ts=4 sw=4
syntax on
set number
set showmatch

"highlight ColorColumn ctermbg=lightgrey guibg=lightgrey
"set colorcolumn=72

" Switch on filetype detection and loads 
" indent file (indent.vim) for specific file types
"filetype indent on
filetype on
"set autoindent " Copy indent from the row above
"set si " Smart indent

" Ignore case in searches
set ic

""""""""""""""""""""""""""""""""""
" Some other confy settings
""""""""""""""""""""""""""""""""""
" set nu " Number lines
set hls " highlight search
set lbr " linebreak


" Key mappigns

" set special keys
map  <Esc>[7~ <Home>
map  <Esc>[8~ <End>
imap <Esc>[7~ <Home>
imap <Esc>[8~ <End>

" exit and write key mappings
nmap <C-W> :w<CR>


" tab manipulation
nnoremap <C-j> :tabprev<cr>
nnoremap <C-k> :tabnext<cr>

" copy paste bindinds
nnoremap <C-a> yG
nnoremap <C-p> p

" yw y$ - yank til end of word or file

hi CursorLine   cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white
hi CursorColumn cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white
nnoremap <Leader>c :set cursorline! cursorcolumn!<CR>
