- name: Install required packages
  become: yes
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - ack-grep
    - acpi
    - acpi-call-dkms
    - apt-listbugs
    - apt-listchanges
    - apt-transport-https
    - awscli
    - borgbackup
    - build-essential
    - ca-certificates
    - cmake
    - curl
    - dos2unix
    - fonts-powerline
    - fonts-symbola
    - git
    - gnome-shell-extension-redshift
    - gnome-tweak-tool
    - gnupg
    - gnupg2
    - hddtemp
    - hplip
    - hplip-gui
    - htop
    - icedove
    - iftop
    - inotify-tools
    - ipython
    - jq
    - kazam
    - keepassx
    - libcurl4-gnutls-dev
    - libgtk2.0-dev
    - libgtk-3-dev
    - libpango1.0-dev
    - libnotify-dev
    - libcairo-dev
    - libffi-dev
    - libgit2-dev
    - libicu-dev
    - libmysqlclient-dev
    - libnotify-bin
    - libpcre3-dev
    - libpq-dev
    - libssl-dev
    - libtinfo-dev
    - lm-sensors
    - make
    - mc
    - nfs-kernel-server
    - pandoc
    - diodon
    - pass
    - pcsc-tools
    - pcscd
    - pdftk
    - pidgin
    - pkg-config
    - python-dev
    - python-notify2
    - python-pip
    - python-virtualenv
    - pwgen
    - redshift
    - redshift-gtk
    - rsync
    - ruby-dev
    - ruby-sass
    - rxvt-unicode-256color
    - scdaemon
    - sudo
    - ssh
    - tmate
    - todotxt-cli
    - tp-smapi-dkms
    - ttyrec
    - unrtf
    - units
    - vagrant
    - vim
    - vim-gnome
    - vim-nox
    - virtualbox
    - weechat
    - weechat-plugins
    - weechat-perl
    - weechat-python
    - wget
    - xserver-xorg-input-synaptics
    - ykneomgr
    - yubikey-personalization
    - wireshark
    - zsh

- name: Install PIL deps
  become: yes
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - libfreetype6-dev
    - libjpeg-dev
    - liblcms2-dev
    - libtiff5-dev
    - libtk-img-dev
    - zlib1g-dev

- name: Install global pip packages
  become: yes
  pip: name={{ item }}
  with_items:
    - subliminal
    - websocket-client # Needed for weechat plugin wee-slack

- name: Install tlp packages
  become: yes
  apt: name={{ item }} state=installed
  with_items:
    - acpi-call-dkms
    - tlp
    - tlp-rdw
    - tp-smapi-dkms

- name: Install virtualenvwrapper
  become: yes
  pip: name=virtualenvwrapper

- name: Make sure lid close only locks the screen, not hibernate
  become: yes
  copy: src=logind.conf dest=/etc/systemd/logind.conf

- name: Enable Trackpoint middle click scrolling
  become: yes
  copy: src=usr_share_x11_xorg.conf.d_20-thinkpad.conf dest=/usr/share/X11/xorg.conf.d/20-thinkpad.conf

- name: Tweak Trackpoint sensitivity and speed
  become: yes
  copy: src=etc_udev_rules.d_10-trackpoint.rules dest=/etc/udev/rules.d/10-trackpoint.rules

- name: Make gnome-shell title bars smaller
  copy: src=config_gtk-3.0_gtk.css dest=/home/deni/.config/gtk-3.0/gtk.css owner=deni group=deni

- name: Make sure to link urxvt config
  file: src=/home/deni/dotfiles/Xresources dest=/home/deni/.Xresources owner=deni group=deni state=link

- name: Link urxvt dir
  file: src=/home/deni/dotfiles/urxvt dest=/home/deni/.urxvt owner=deni group=deni state=link

- name: Link mc config
  file: src=/home/deni/dotfiles/mc dest=/home/deni/.config/mc owner=deni group=deni state=link

- name: Link ansible.cfg
  file: src=/home/deni/dotfiles/ansible.cfg dest=/home/deni/.ansible.cfg owner=deni group=deni state=link

- name: Link todo config
  file: src=/home/deni/dotfiles/todo dest=/home/deni/.todo owner=deni group=deni state=link

- name: Link gitconfig
  file: src=/home/deni/dotfiles/gitconfig dest=/home/deni/.gitconfig owner=deni group=deni state=link

- name: Link flake8 config
  file: src=/home/deni/dotfiles/flake8 dest=/home/deni/.config/flake8 owner=deni group=deni state=link

- name: Link ghci config
  file: src=/home/deni/dotfiles/ghci dest=/home/deni/.ghci owner=deni group=deni state=link

- name: Link redshift config
  file: src=/home/deni/dotfiles/redshift.conf dest=/home/deni/.config/redshift.conf owner=deni group=deni state=link

- name: install oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/home/deni/.oh-my-zsh update=no

- name: link zshrc
  file: src=/home/deni/dotfiles/zshrc dest=/home/deni/.zshrc owner=deni group=deni state=link

- name: link vimperatorrc
  file: src=/home/deni/dotfiles/vimperatorrc dest=/home/deni/.vimperatorrc owner=deni group=deni state=link

- name: Auto load wifi headset on connect
  become: yes
  copy: src=etc_pulse_default.pa dest=/etc/pulse/default.pa

- name: Make autoload wifi headset changes take effect (if not already loaded)
  shell:  pacmd list-modules | if ! (grep -q "module-switch-on-connect2" - ); then pacmd load-module module-switch-on-connect; fi

- name: Check if powerline fonts are installed
  shell: fc-list | grep -q "Inconsolata\ for\ Powerline"
  register: powerline

- name: Clone powerline repo
  git: repo=https://github.com/powerline/fonts dest=/tmp/powerline accept_hostkey=yes
  when: powerline.rc != 0

- name: Install powerline fonts
  shell: cd /tmp/powerline && ./install.sh
  when: powerline.rc != 0

- name: Remove powerline repo
  file: path=/tmp/powerline state=absent

- name: Create common mount point dirs
  become: yes
  file: path={{ item }} state=directory owner=deni group=deni
  with_items:
    - /media/varys/torrents
    - /media/varys/backups

- name: Remove pcspkr module
  become: yes
  modprobe: name=pcspkr state=absent

- name: Make sure pcspkr module does not get loaded on boot
  become: yes
  kernel_blacklist: name=pcspkr state=present

- name: Make sure screenshot directory exists
  file: path="{{ screenshot_dir }}" state=directory owner={{ default_user }} group={{ default_group }}

- name: Get gnome screenshot folder
  shell: gsettings get org.gnome.gnome-screenshot auto-save-directory
  register: screenshot_dir_check

- name: Set gnome screenshot folder
  shell: gsettings set org.gnome.gnome-screenshot auto-save-directory "file:///{{ screenshot_dir }}"
  when: screenshot_dir_check.stdout == "''"

- name: Check if fzf is installed
  shell: fzf --version
  ignore_errors: True
  register: fzf_is_installed

- name: Download fzf binary
  become: yes
  get_url:
    url: "{{ fzf_artifact_url }}"
    dest: /tmp/fzf.tgz
    mode: 0755
  when: (fzf_is_installed.rc != 0) or (fzf_version not in fzf_is_installed.stdout)

- name: Extract fzf and make executable
  become: yes
  unarchive: src=/tmp/fzf.tgz dest=/usr/local/bin mode=755 owner=root group=root
  when: (fzf_is_installed.rc != 0) or (fzf_version not in fzf_is_installed.stdout)

