- name: Install required packages
  become: yes
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - ack-grep
    - acpi-call-dkms
    - apt-transport-https
    - build-essential
    - ca-certificates
    - cmake
    - cryptkeeper
    - curl
    - fonts-powerline
    - git
    - gnome-shell-extension-redshift
    - hplip
    - htop
    - icedove
    - iftop
    - keepassx
    - make
    - mc
    - parcellite
    - pidgin
    - python-dev
    - python-pip
    - python-virtualenv
    - redshift
    - redshift-gtk
    - rxvt-unicode-256color
    - sudo
    - tlp
    - tp-smapi-dkms
    - vim
    - vim-gnome
    - vim-nox
    - weechat
    - wget
    - zsh

- name: Install global pip packages
  become: yes
  pip: name={{ item }}
  with_items:
    - subliminal

- name: Install virtualenvwrapper
  become: yes
  pip: name=virtualenvwrapper

- name: Make sure lid close only locks the screen, not hibernate
  become: yes
  copy: src=logind.conf dest=/etc/systemd/logind.conf

- name: Enable Trackpoint middle click scrolling
  become: yes
  copy: src=usr_share_x11_xorg.conf.d_20-thinkpad.conf dest=/usr/share/X11/xorg.conf.d/20-thinkpad.conf

- name: Tweak Trackpoint sensitivity and speed
  become: yes
  copy: src=etc_udev_rules.d_10-trackpoint.rules dest=/etc/udev/rules.d/10-trackpoint.rules

- name: Make gnome-shell title bars smaller
  file: src=config_gtk-3.0_gtk.css dest=/home/deni/.config/gtk-3.0/gtk.css owner=deni group=deni

- name: Make sure to link urxvt config
  file: src=/home/deni/dotfiles/Xdefaults dest=/home/deni/.Xdefaults owner=deni group=deni state=link

- name: install oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/home/deni/.oh-my-zsh update=no

- name: link zshrc
  file: src=/home/deni/dotfiles/zshrc dest=/home/deni/.zshrc owner=deni group=deni state=link

- name: Auto load wifi headset on connect
  become: yes
  file: src=etc_pulse_default.pa dest=/etc/pulse/default.pa

- name: Make autoload wifi headset changes take effect (if not already loaded)
  shell:  pacmd list-modules | if ! (grep -q "module-switch-on-connect2" - ); then pacmd load-module module-switch-on-connect; fi
