---
- name: Add Tarsnap apt key
  become: yes
  apt_key: url="{{ tarsnap_debian_apt_repo_key_url }}" state=present

- name: Add Tarsnap debian apt repo
  become: yes
  apt_repository: repo="{{ tarsnap_debian_apt_repo }}" state=present

- name: Install tarsnap package
  become: yes
  apt: name={{item}} state=installed
  with_items:
    - tarsnap
    - tarsnap-archive-keyring
