
- name: Make sure the user is in the correct groups has the correct shell
  become: yes
  user: name=deni shell=/usr/bin/zsh groups=geoclue,docker,lpadmin append=yes

- name: Add battery watch crontab
  cron:
    name: "Check battery"
    user: deni
    job: "/home/deni/dotfiles/scripts/battery_watch.sh"

