---
vault_version: 1.3.2
vault_artifact_url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
vault_artifact_sha: "sha256:6e72132de0421b74d909f50be1823fe57182694c4268ba9a38c31213d9497ec9"
