#!/bin/bash

# env
# export QT_ACCESSIBILITY=1
# export QT_SCALE_FACTOR=2
#export GDK_SCALE=2

# Xresources
xsetroot -cursor_name left_ptr &

# This replaces gnome-settings-daemon 8.21.2017.
/usr/lib/gnome-settings-daemon/gsd-xsettings &
# /usr/lib/gnome-settings-daemon/gsd-a11y-setting &
# /usr/lib/gnome-settings-daemon/gsd-housekeeping &
# /usr/lib/gnome-settings-daemon/gsd-sound &

eval $(gnome-keyring-daemon --start)
xscreensaver -nosplash &
feh --bg-scale /home/deni/walls/droid.png &
synclient TouchpadOff=1 &
xmodmap ~/.Xmodmap &

# Startup apps
trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 20 --transparent true --tint 0x222222 --heighttype pixel --height 20 &
parcellite &
redshift -c /home/deni/dotfiles/redshift.conf &
dunst &
nm-applet &
dropbox start &
run_keybase &
#conky -X ":0.0" &
# synology-cloud-station-drive &

