#!/bin/bash
# DEPRECATED: This file was only used on Debian.
# With NixOS + home-manager, we use systemd user services instead.

# env
# Integer only
# export GDK_SCALE=2
# Can handle floats
# export GDK_DPI_SCALE=2
#export QT_FONT_DPI=210

# Xresources
xsetroot -cursor_name left_ptr &
picom &

# This replaces gnome-settings-daemon 8.21.2017.
#/usr/lib/gnome-settings-daemon/gsd-xsettings &
# /usr/lib/gnome-settings-daemon/gsd-a11y-setting &
# /usr/lib/gnome-settings-daemon/gsd-housekeeping &
# /usr/lib/gnome-settings-daemon/gsd-sound &

eval $(gnome-keyring-daemon --start)
xscreensaver -nosplash &
feh --bg-scale /home/deni/walls/hack5.png &
synclient TouchpadOff=1 &
xmodmap ~/.Xmodmap &

# Startup apps
trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 20 --transparent true --alpha 0 --tint 0x222222 --height 40 &

# Tried diodon instead of parcellite because parcellite has scaling issues
# XDG_CURRENT_DESKTOP=GNOME parcellite &
# this one is writen in haskell and integrates great with rofi
# MOVED: to systemd user service
# greenclip daemon &

# Fork of parcellite: https://github.com/CristianHenzel/ClipIt
# Fixes scaling issues
# clipit &

# NOTE: fix dbus and geoclue error
# redshift -c /home/deni/dotfiles/redshift.conf &

dunst -config ~/.config/dunst/dunstrc &
dbus-launch nm-applet &
blueman-applet &
dropbox start &
# run_keybase &
#conky -X ":0.0" &
# synology-cloud-station-drive &

