- name: Add Spideroak apt key
  become: yes
  apt_key: url="{{ spideroakone_debian_apt_repo_key_url }}" state=present validate_certs=no

- name: Add Spideroak debian apt repo
  become: yes
  apt_repository: repo="{{ spideroakone_debian_apt_repo }}" state=present

- name: Install spideroakone package
  become: yes
  apt: name=spideroakone state=installed

