- name: Add Docker apt key
  become: yes
  apt_key: keyserver="{{ docker_debian_apt_repo_keyserver_url }}" id="{{ docker_debian_apt_repo_key_id }}"

- name: Install docker apt repo
  become: yes
  apt_repository: repo="{{ docker_debian_apt_repo }}" state=present

- name: Install Docker and Docker Compose
  become: yes
  apt: pkg={{ item }} state=installed
  with_items:
    - docker-engine

