- name: Add Docker apt key
  become: yes
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: Install docker apt repo
  become: yes
  copy: src=docker.list dest=/etc/apt/sources.list.d/docker.list

- name: Update apt cache
  apt: update_cache=yes
  become: yes
  ignore_errors: True

- name: Install Docker and Docker Compose
  become: yes
  apt: pkg={{ item }} state=installed
  with_items:
    - docker-engine
    - docker-compose

