
- name: Laptop
  hosts: localhost
  user: deni
  roles:
    - { role: common, tags: ["common"] }
    - { role: vim, tags: ["vim"] }
    - { role: dropbox, tags: ["dropbox"] }
    - { role: google-chrome, tags: ["google-chrome"] }
    - { role: spideroakone, tags: ["spideroakone"] }
    - { role: haskell, tags: ["haskell"] }
    - { role: docker, tags: ["docker"] }
    - { role: keybase, tags: ["keybase"] }
    - { role: terraform, tags: ["terraform"] }
    - { role: packer, tags: ["packer"] }
    - { role: vault, tags: ["vault"] }
    - { role: sops, tags: ["sops"] }
    - { role: xmonad, tags: ["xmonad"] }
    - { role: kube, tags: ["kube"] }
    - { role: tarsnap, tags: ["tarsnap"] }
    - { role: zerotier, tags: ["zerotier"] }
    - { role: user, tags: ["user"] } # This needs to be the last role because
                                     # we add the user to groups that might not
                                     # exist yet if not installed by roles above!

